### ISSUE TITLE
Problem button 2 (S2)

### ISSUE THREAD

**Issue by capsule5000** [fbelavenuto/msxsdmapperv2#4]
I have assembled the PCB and it works fine, and the S1 button also works fine because it enables/disables the 512K.  But the switch S2 apparently doesn't seem to work.  When it is active, it does not load the driver that detects SD cards.  Is that operation correct?

In the readme.md it says something like " A segunda chave permite selecionar entre duas opções de driver, útil para se ter um backup de uma versão estável do driver e utilizá-lo para restaurar um driver novo com falha na atualização. " but I don't understand how it works correctly.  In version1 it activated or deactivated the megaram..... In version2 S2 does it work differently?  All the best!

**Comment by sdsnatcher** [comment]
The switch S2 has a different function on SD-Mapper v2. Translating (with some improvements for better comprehension):

"The second switch allows the selection of two different firmwares. This is useful to have a stable version of the firmware, and use it to restore the other firmware in case there's a problem on the update".

It can also be used to have two different versions of the Nextor ROM. One beta and one stable.

The ROM update utility FBL-UPD.COM will ask you to set this switch to select witch of the two firmwares you want to be updated.

**Comment by capsule5000** [comment]
Thank you very much for the reply!!. I have another question regarding the answer. I've tried to test with the FBL-UPD.COM command, such as put in the example fbl-upd sdmapper.rom, and every time I get an error message that "ops...cannot find interface". I have tried selecting it manually with the command fbl-upd /s sdmapper.rom and it gives me the same error that it cannot find the interface. It is tried from the sdmapper slot1 itself and it does not work. With a floppy (running fbl-upd) and sdmapperv2 slot1 and it doesn't work either, with carnivore2 (running fbl-upd) slot1 and sdmapperv2 slot2 and it doesn't work either.
What is the procedure to run the fbl-upd.com command? Can it be done from the sdmapperv2 slot1 itself or does the sdmapper have to be in slot2 and run the command from a floppy or other device connected to slot1?

**Comment by cristianoag** [comment]
Hi capsule. I built a few of those already and it looks like your cartridge is still not 100% alive. I believe you programmed the CPLD without any issues otherwise you should not be in the step to lkoad the BIOS to the flash. It doesn’t matter the slot. The fbl-upd.com program works in any of them. A few things I recommend you to check.


  1.  The oscillator. Get your scope and check if the crystal is oscillating. You can program the CPLD even if the crystal is not ok and it is usually a source of trouble as the pads are harder to get the right contact with the PCB.
  2.  Check again if all the pads for the memory and flash are soldered correctly. I used sockets for the flash last time I built those sd mappers and I figured out they are better than trying to solder the SOJ flash chips against SMD pads.
  3.  Make sure your chips are working ok. That is a hard one when buying components from China, but I need to ask. 😊 I had cases where my CPLDs were programmed correctly with ISE but when looking into the thermal camera you can see a odd hot spot at the center of the chip. That is not normal.
Cristiano.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by capsule5000** [comment]
I confirm that I have mounted 2 sdmapper512 v2 and both apparently work correctly. The nextor runs correctly, I have access to the 2 SD cards, and I press S1 to activate the 512k and if I activate S2 in one position it loads the SD card driver and in the other position it does not load it. Up to this point everything works fine and I can run apps and games.

I just wanted to experiment with the FBL-UPD command, because I like to see all the options that the project developer gives, but I find that there is no way for the command to detect the sdmapperv2 card.

I try it by putting sdmapper in slot1 and running FBL-UPD from floppy and it doesn't detect it.

I try to execute the FBL-UPD command from the sdmapper 512v2 itself connected to slot1 and it does not detect it either

and the last test is to run FBL-UPD from carnivore2/flashjacks/multicontroller in slot1 and sdmapper512v2 in slot2 and it doesn't detect the card either.

I don't know what the problem is and why it doesn't detect the sdmapper512v2 card and everything works correctly

**Comment by cristianoag** [comment]
Are you using the correct version? I only use it to update mine. It works ok every time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by capsule5000** [comment]
I use the FBL-UPD.COM command, and the ROM SDMAPPER.ROM only from the version2 repository, and neither automatically nor manually is it able to detect the sdmapper512v2 card.  

Cristianoag how do you update the sdmapper512v2 rom?  The instruction would be: FBL-UPD SDMAPPER.COM......is that correct?

Do you update it by executing the FBL-UPD command from the sdmapper512v2 card itself in slot 1?  or do you run it from another device example floppy and the sdmapper512v2 card in slot1? 

 How do you update it?

**Comment by cristianoag** [comment]
That is correct. Just fbl-upd sdmapper.rom. I run it from another place. Usually from my fpga based msx microsd card.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cristianoag** [comment]
Are you using sf or vf flash ics? Can you post a picture of your pcb or list exactly the ic codes you are using?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fbelavenuto** [comment]
Hi, what is the flash chip model used?

**Comment by capsule5000** [comment]
The chip used for ROM that I have installed is the SST39VF020. In the project BOM specify SST39VF020N. The problem may be that my chip is not the model ending in N? When I record it with the TL866II plus programmer, it records everything correctly and as I said, the board works perfectly, it does not have any operating errors, only that the FBL-UPD command does not detect the card.
[https://imgur.com/JvSvSKp.jpeg](url)
[https://imgur.com/G3CrZNK.jpeg](url)

**Comment by cristianoag** [comment]
Replace the one you are using by the 39S or any AMF29F and the programming tool will work. The 39V ones are 2.7-3.6V single voltage r/w and the tool drives signals that are not on the pattern and voltage expected by them. If you use 39V you will need to program them on a TL866 programmer.

Cristiano

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by capsule5000** [comment]
Problem solved!! As Cristianoag commented, the SST29VF020 EEPROM can only be programmed using a tl866 II plus type programmer. Using the AM29F010B EEPROM, the same one used for the sdmapper512k_v1, it can be programmed using a TL866 II plus type programmer or using the MSX-DOS command FBL-UPD.COM
