### ISSUE TITLE
Yis503III and memory mapper

### ISSUE THREAD

**Issue by serperus** [fbelavenuto/msxsdmapperv2#7]
Hi,
After assembling the cartrige I checked it on Omega MSX and it works great, both SD are visible and addditional 512k RAM - ok.
But I can't run it on YIS503-III Yamaha,
SD cards are detected, nextor runs good to dos,  but 512k RAM - not visible.
Any game from sofarun says out of free segments, and testmap can't see additional mapper in slot.

Is it compatible with this msx machine?
Thanks!

Serge

**Comment by fbelavenuto** [comment]
Hello, sorry for the delay. I don't have a YIS503-III to test, but it is possible that there is incompatibility with this model. Some MSX models that I had access to test are incompatible with SDMapper.

**Comment by serperus** [comment]
Hi,
The problem was solved by adding additional internal 1M to YIS503 machine :)
512k still not visible, but sd works.
